### ISSUE TITLE
Email confirmation link didn't work

### ISSUE THREAD

**Issue by benfrancis** [WebThingsIO/registration_server#77] opened 2018-10-05 14:26 UTC
A user reported that they received an email confirmation email that:
1. Wasn't a clickable hyperlink
2. When they copy-pasted it into the browser, the URL failed to load with a security error

That was all the information they gave.

**Comment by mrstegeman** [comment] 2018-10-12 12:38
The first issue should now be fixed. We've had reports of the second before, but I've never been able to reproduce. When given the "broken" URL, I've always been able to reach it.

**Comment by kgiori** [comment] 2019-01-02 22:09
the inability to click directly from the e-mail and see the confirmation page in the browser happens to me because the browser tries to redirect to `https://api...`

but if I copy and paste the e-mail URL into a "New Private Window" when using Firefox, then it succeeds.

**Comment by mrstegeman** [comment] 2019-01-03 15:41
For some reason, some users are getting redirected to `https://api.mozilla-iot.org`, without the `:8443` appended. Trying to figure out what's going on.

**Comment by mrstegeman** [comment] 2019-01-03 16:07
I made some changes on the server. Guess we'll have to wait and see if this is fixed. Everything works for me, but it always has.

**Comment by mrstegeman** [comment] 2019-02-06 13:24
I'm going to call this fixed now. Let's re-open if we see this again.

**Closed as completed by mrstegeman** 2019-02-06 13:24 UTC
Labels: bug
